### ISSUE TITLE
phy.plot enhancements

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/phy#666]
### General
- [x] Text support on VisPy views
- [ ] "Selected view" notion with selected view highlighted (and gettable via a GUI method)
### WaveformView
- [ ] Auto-rescaling https://github.com/kwikteam/phy/issues/401 https://github.com/kwikteam/phy/issues/94
- [ ] Boxes around waveforms to show currently/automatically selected features (to FeatureView)
- [x] Option to show template
### FeatureView / FeatureGridView
- [x] Show text for selected features https://github.com/kwikteam/phy/issues/164
- [ ] Allow horizontal splitting https://github.com/kwikteam/phy/issues/471
- [ ] Auto-rescale so 99% of features take up 80% of view
- [ ] Highlight spikes which violate ISI (interval settable via snippet etc) https://github.com/kwikteam/phy/issues/473
### Cluster/WizardView
- [x] Actually do it... https://github.com/kwikteam/phy/issues/645
### ISIView
- [x] Do it... https://github.com/kwikteam/phy/issues/190
### TraceView

https://github.com/kwikteam/phy/issues/474
- [x] Jump to next spike in selected cluster(s) with Ctrl+arrow
- [ ] Show filtered data (realtime filtering with same parameters as spike detection, or using filtered data source)
- [ ] Jump to next simultaneous occurrence of spikes / all selected clusters with Ctrl+Shift+Arrow (hopefully this will be fast enough!) - within viewport aka 500ms etc
- [x] Show all spikes (not just selected clusters) by pressing S
- [ ] Only show unmasked channels for cluster(s) which are selected. With 300 channels it's carnage
